spring.application.name=overview

spring.datasource.url=jdbc:mysql://localhost:3307/overview?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/docs


spring.jwt.secret=c8545a69cf9ed0671e63dc61a7bfa81a242b2736014537d5dacaea317b06a284
spring.jwt.expiration=1_800_000