spring.application.name=overview

spring.datasource.url=jdbc:mysql://localhost:3307/overview?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/docs

logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG


spring.jwt.secret=2y8wSmX062BHsYygfJZHcrCuhG8iZeWOfHMXXJnwZe9/DuOC79abTQIZ88TQJePNikGDUHFjnIRcG1KiaqSkuQ==
spring.jwt.expiration=1800000